[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200

upload_protocol = esptool
upload_port = COM5

; Opções de compilação para otimizar o processamento do ESP32
build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; Aqui é onde você declara as bibliotecas. 
; Já deixei a FastAccelStepper engatilhada caso você queira testá-la depois.
lib_deps =
    ; gin66/FastAccelStepper @ ^0.30.15